name: fu24_block2_team3_env
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python=3.8
  - dataprep
  - pyarrow-hotfix
