name: fu24_block2_team3_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python=3.11
